### ISSUE TITLE
Addition for Conferences and workshops

### ISSUE THREAD

**Issue by ookgezellig** [shigapov/wikibase-knowledge-graphs#1]
An addition for [Conferences and workshops](https://github.com/shigapov/wikibase-knowledge-graphs#conferences-and-workshops)

https://www.ghentcdh.ugent.be/ghent-university-wikidata-and-wikibase-workshop-developing-wikibase-instance-3-5-july-2019

**Comment by ookgezellig** [comment]
https://www.wikidata.org/wiki/Wikidata:Events/Belgium/Universiteit_Gent/Wikidata_and_Wikibase_Workshop/2019

**Comment by shigapov** [comment]
Thank you!

**Comment by shigapov** [comment]
added
